name: Build AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-gi python3-gi-cairo gir1.2-gtk-3.0 nmap desktop-file-utils libgdk-pixbuf2.0-dev

    - name: Install Python dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Create AppImage
      run: |
        chmod +x build/build-appimage.sh
        ./build/build-appimage.sh

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v3
      with:
        name: Network-Service-Scanner-AppImage
        path: Network-Service-Scanner-*.AppImage

    - name: Upload AppImage to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: Network-Service-Scanner-*.AppImage
        asset_name: Network-Service-Scanner-${{ github.event.release.tag_name }}-x86_64.AppImage
        asset_content_type: application/octet-stream